import L from 'leaflet';
import './style.css';

declare global { interface Window { ODP_TOKEN: string } }
type Coord=[number,number];
type Settings=Record<string,number|string|boolean|null>;
type Waypoint={lon:number;lat:number;alt:number;speed:number;gimbal:number;heading:number|null;action:string;hover:number;ground:number|null;unsupported?:string[];gimbalEnd?:number};
type Shape={kind:'area'|'exclusion'|'corridor'|'poi';coords:Coord[]};
type Profile={aircraft:string;sub:string;name:string;namespace:string;config:string};
type Mission={id?:string;version:number;name:string;mode:string;settings:Settings;shapes:Shape[];points:Waypoint[];home:Coord|null;profile:Profile|null;heightMode:string;area?:number;terrainSource?:string|null;sourceOriginal?:string;importNotes?:string[]};
type Report={errors:string[];warnings:string[];distance:number;seconds:number;photoCount:number;waypoints:number;area:number;batteryUsableSeconds:number;estimatedBatteries:number;footprint:{width:number;height:number;spacing:number;photoSpacing:number;gsd:number}};
type Library={missions:(Mission&{id:string})[];presets:{id:string;name:string;settings:Settings}[]};
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const clone=<T>(v:T):T=>structuredClone(v);
async function api<T>(path:string,body?:unknown):Promise<T>{
 const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:{'X-ODP-Token':window.ODP_TOKEN,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
 const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');return data as T;
}
let activeJobs=0;
async function job<T>(path:string,body:unknown,label:string):Promise<T>{
 activeJobs++;$('busy-status').textContent=label;$('busy-status').classList.remove('hidden');
 try{const {job:id}=await api<{job:string}>(path,body);for(;;){const j=await api<{done:boolean;result:T}>('job/'+id);if(j.done)return j.result;await new Promise(r=>setTimeout(r,700));}}
 finally{activeJobs--;if(!activeJobs)$('busy-status').classList.add('hidden');}
}
let toastTimer:ReturnType<typeof setTimeout>;
function toast(message:string,bad=false){$('toast').textContent=message;$('toast').className='toast'+(bad?' bad':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),bad?12000:5000);}
function handle(fn:()=>Promise<void>|void){return ()=>{try{Promise.resolve(fn()).catch(e=>toast(String(e.message||e),true));}catch(e){toast(String(e),true);}};}
let defaults:Settings={},profile:Profile|null=null;
let m:Mission;let savedId:string|undefined;let tab='plan';let report:Report|null=null;
let tool='select';let drawing:Coord[]=[];let shapeIndex=-1;let selected=new Set<number>();let history:Mission[]=[];let future:Mission[]=[];
let renderedTab='';
let library:Library={missions:[],presets:[]};let unit=localStorage.getItem('odp-units')||'m';let reviewSequence=0;
let simTimer:ReturnType<typeof setInterval>|null=null;let simMarker:L.Marker|null=null;
const base=()=>({version:1,name:'Untitled mission',mode:'survey',settings:clone(defaults),shapes:[],points:[],home:null,profile:clone(profile),heightMode:'relativeToStartPoint'}) as Mission;
const factor=()=>unit==='ft'?3.280839895:1;
const distanceLabel=(n:number)=>unit==='ft'?(n*factor()).toFixed(0)+' ft':n>=1000?(n/1000).toFixed(2)+' km':n.toFixed(0)+' m';
const heightLabel=(n:number)=>(n*factor()).toFixed(0)+' '+unit;
const stamp=()=>{history.push(clone(m));if(history.length>60)history.shift();future=[];};
const numeric=(key:string)=>Number(m.settings[key]);
let draftSave:Promise<unknown>=Promise.resolve();
function persist(){const snapshot=clone(m);draftSave=draftSave.catch(()=>{}).then(()=>api('draft',{mission:snapshot})).catch(()=>{$('save-state').textContent='Save the mission to preserve this draft.';});try{localStorage.setItem('odp-draft',JSON.stringify(m));$('save-state').textContent='Draft saved on this computer';}catch{$('save-state').textContent='Draft too large. Save to library.';}}
async function changed(render=true){stopSimulation();persist();if(render){renderPanel();renderMap();}const seq=++reviewSequence;try{const value=await api<Report>('review',{mission:m});if(seq===reviewSequence){report=value;renderStats();if(tab==='review')renderPanel();}}catch(e){if(seq===reviewSequence){report=null;renderStats();toast(String(e),true);}}}
function newPoint(c:Coord):Waypoint{return {lon:c[0],lat:c[1],alt:numeric('altitude'),speed:numeric('speed'),gimbal:numeric('gimbal'),heading:null,action:String(m.settings.action),hover:0,ground:null};}
function invalidateTerrain(){m.terrainSource=null;m.settings.terrain=false;m.settings.homeElevation=null;for(const p of m.points)p.ground=null;}
function loadMission(value:Mission,id?:string){stamp();m=clone(value);savedId=id||value.id;selected.clear();shapeIndex=-1;drawing=[];tool='select';$('mission-name').setAttribute('value',m.name);($('mission-name') as HTMLInputElement).value=m.name;void changed();fit();}

document.querySelector('#app')!.innerHTML=`
<header class="topbar"><div class="brand"><img src="/icon.svg" alt=""><div><b>OpenDronePlanner</b><small>Your mission, clearly planned</small></div></div><input id="mission-name" class="title-input" aria-label="Mission name" value="Untitled mission"><div class="top-actions"><button id="mobile" class="mobile-toggle" aria-label="Open planning panel">Plan</button><button id="new">New</button><button id="import">Import</button><button id="save">Save</button><button id="top-review" class="primary">Review & export</button><button id="help" class="help-button" aria-label="Help">?</button></div></header>
<div class="workspace"><aside class="sidebar" id="sidebar"><nav class="tabs" aria-label="Planning stages"><button data-tab="plan" class="active">01 · Plan</button><button data-tab="points">02 · Route</button><button data-tab="review">03 · Review</button><button data-tab="library">Library</button></nav><div id="panel"></div><div class="sidebar-footer"><i class="dot"></i><span id="save-state">Local workspace · no account needed</span></div></aside>
<main class="canvas-area"><div id="map" aria-label="Flight planning map"></div><form class="map-search" id="search-form"><input id="search" placeholder="Find a place or enter latitude, longitude" aria-label="Search location"><button type="submit">Find</button></form><div id="search-results" class="search-results"></div>
<div class="map-tools" aria-label="Map drawing tools"><button data-tool="select" title="Select and drag waypoints">Select</button><button data-tool="area">Polygon</button><button data-tool="rectangle">Rectangle</button><button data-tool="corridor">Corridor</button><button data-tool="exclusion">Exclude</button><span class="divider"></span><button data-tool="waypoint">Waypoint</button><button data-tool="poi">POI</button><button data-tool="home">Takeoff</button></div>
<div id="map-help" class="map-help"></div><div id="busy-status" role="status" class="hidden"></div><div class="map-bottom-tools"><button id="undo" title="Ctrl+Z">↶ Undo</button><button id="redo" title="Ctrl+Shift+Z">↷ Redo</button><button id="fit">Fit route</button><button id="simulate">▶ Preview</button></div>
<div class="stats" id="stats"></div><div class="profile"><div class="profile-title"><span>ALTITUDE PROFILE · RELATIVE TO TAKEOFF</span><span id="profile-source">Terrain not loaded</span></div><svg id="profile" role="img" aria-label="Waypoint altitude and ground profile"></svg><div id="profile-empty" class="empty">Your route and terrain profile will appear here</div></div></main></div>
<div id="toast" class="toast hidden" role="status"></div><dialog id="dialog"></dialog><input type="file" id="file" class="hidden" accept=".kmz,.kml,.json,.geojson"><input type="file" id="profile-file" class="hidden" accept=".kmz"><input type="file" id="dem" class="hidden" accept=".tif,.tiff"><div id="drop-overlay" class="drop-overlay hidden">Drop a KMZ, KML, GeoJSON or ODP project to plan</div>`;
const map=L.map('map',{zoomControl:false,doubleClickZoom:false,preferCanvas:true,maxZoom:22}).setView([39.2191,-121.0611],14);
L.control.zoom({position:'topright'}).addTo(map);L.control.scale({imperial:true,metric:true}).addTo(map);
const streets=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:22,maxNativeZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);
const satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:22,maxNativeZoom:19,attribution:'Imagery © Esri, Maxar, Earthstar Geographics, GIS User Community'});
const topo=L.tileLayer('https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/{z}/{y}/{x}',{maxZoom:22,maxNativeZoom:16,attribution:'USGS The National Map'});
L.control.layers({'Street map':streets,'Satellite':satellite,'USGS topo':topo},{},{position:'topright'}).addTo(map);
for(const layer of [streets,satellite,topo])layer.on('tileerror',()=>{$('profile-source').title='Some background map tiles could not load. Planning geometry is still available.';});
const shapesLayer=L.layerGroup().addTo(map),routeLayer=L.layerGroup().addTo(map),drawLayer=L.layerGroup().addTo(map);
const latlng=(c:Coord):L.LatLngTuple=>[c[1],c[0]];
function fit(){const cs=[...m.points.map(p=>[p.lon,p.lat] as Coord),...m.shapes.flatMap(s=>s.coords),...(m.home?[m.home]:[])];if(cs.length)map.fitBounds(L.latLngBounds(cs.map(latlng)),{padding:[70,140],maxZoom:22});}
function setTool(value:string){tool=value;drawing=[];shapeIndex=-1;drawLayer.clearLayers();renderMap();renderHelp();}
function renderHelp(){
 document.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));
 const hints:Record<string,string>={select:m.points.length?'Drag a waypoint to adjust it. Ctrl-click selects several. Shift-drag selects and zooms to a group.':'Start by drawing a boundary, or import an existing flight.',area:'Click the boundary corners, then finish the polygon.',rectangle:'Click two opposite corners of your survey rectangle.',corridor:'Click along the route, then finish the corridor.',exclusion:'Outline the area to avoid. Include your own clearance buffer.',waypoint:'Click to add waypoints in flight order.',poi:'Click the subject to create an orbit center.',home:'Click the actual takeoff location. This anchors altitude and return estimates.'};
 $('map-help').innerHTML=esc(hints[tool])+(drawing.length?` <button id="finish-drawing">Finish ${tool}</button><button id="cancel-drawing">Cancel</button>`:'');
 $('finish-drawing')?.addEventListener('click',handle(finishDrawing));$('cancel-drawing')?.addEventListener('click',()=>setTool('select'));
 $('undo').toggleAttribute('disabled',!history.length);$('redo').toggleAttribute('disabled',!future.length);
}
function finishDrawing(){
 const min=tool==='corridor'?2:3;if(drawing.length<min){toast(`Add at least ${min} corners.`,true);return;}
 stamp();m.shapes.push({kind:tool as Shape['kind'],coords:clone(drawing)});shapeIndex=m.shapes.length-1;drawing=[];tool='select';void changed();
}
map.on('click',(e:L.LeafletMouseEvent)=>{
 if(!m)return;const c:Coord=[e.latlng.lng,e.latlng.lat];
 if(tool==='select'){selected.clear();shapeIndex=-1;renderPanel();renderMap();return;}
 if(tool==='waypoint'){stamp();m.points.push(newPoint(c));selected=new Set([m.points.length-1]);invalidateTerrain();void changed();return;}
 if(tool==='home'){stamp();m.home=c;invalidateTerrain();tool='select';void changed();return;}
 if(tool==='poi'){stamp();m.shapes.push({kind:'poi',coords:[c]});m.mode='orbit';tool='select';void changed();return;}
 drawing.push(c);
 if(tool==='rectangle'&&drawing.length===2){const [a,b]=drawing;stamp();m.shapes.push({kind:'area',coords:[[a[0],a[1]],[b[0],a[1]],[b[0],b[1]],[a[0],b[1]]]});drawing=[];tool='select';void changed();return;}
 drawLayer.clearLayers();L.polyline(drawing.map(latlng),{color:'#d59239',dashArray:'5,6'}).addTo(drawLayer);drawing.forEach(c=>L.circleMarker(latlng(c),{radius:4,color:'#d59239'}).addTo(drawLayer));renderHelp();
});
map.on('boxzoomend',(event)=>{const bounds=(event as L.LeafletEvent & {boxZoomBounds:L.LatLngBounds}).boxZoomBounds;selected=new Set(m.points.map((p,i)=>bounds.contains([p.lat,p.lon])?i:-1).filter(i=>i>=0));tab='points';renderPanel();renderMap();});
function renderMap(){
 shapesLayer.clearLayers();routeLayer.clearLayers();if(!drawing.length)drawLayer.clearLayers();
 m.shapes.forEach((sh,i)=>{
  const color=sh.kind==='exclusion'?'#b85a44':sh.kind==='poi'?'#8b6ab5':'#35755a';
  let layer:L.Layer;
  if(sh.kind==='poi')layer=L.marker(latlng(sh.coords[0]),{icon:L.divIcon({className:'poi-pin',html:'◎',iconSize:[28,28]}),draggable:tool==='select'}).on('dragend',e=>{stamp();const p=(e.target as L.Marker).getLatLng();sh.coords[0]=[p.lng,p.lat];void changed();});
  else if(sh.kind==='corridor')layer=L.polyline(sh.coords.map(latlng),{color,weight:8,opacity:.4});
  else layer=L.polygon(sh.coords.map(latlng),{color,weight:shapeIndex===i?3:2,fillOpacity:sh.kind==='exclusion'?.22:.09,dashArray:sh.kind==='exclusion'?'6,5':undefined});
  layer.on('click',(ev)=>{const e=ev as L.LeafletMouseEvent;L.DomEvent.stopPropagation(e.originalEvent);if(tool==='select'){shapeIndex=i;selected.clear();renderPanel();renderMap();}}).addTo(shapesLayer);
  if(shapeIndex===i&&sh.kind!=='poi')sh.coords.forEach((c,j)=>L.marker(latlng(c),{draggable:true,icon:L.divIcon({className:'number-pin selected',html:'',iconSize:[12,12]})}).on('dragstart',()=>stamp()).on('dragend',e=>{const p=(e.target as L.Marker).getLatLng();sh.coords[j]=[p.lng,p.lat];void changed();}).addTo(shapesLayer));
 });
 if(m.points.length){
  L.polyline(m.points.map(p=>[p.lat,p.lon] as L.LatLngTuple),{color:'#fff',weight:5,opacity:.8,interactive:false}).addTo(routeLayer);
  L.polyline(m.points.map(p=>[p.lat,p.lon] as L.LatLngTuple),{color:'#236d50',weight:2.5,opacity:.95,interactive:false}).addTo(routeLayer);
  m.points.forEach((p,i)=>{
   const marker=m.points.length<=750||selected.has(i)?L.marker([p.lat,p.lon],{draggable:tool==='select',icon:L.divIcon({className:'number-pin'+(selected.has(i)?' selected':''),html:String(i+1),iconSize:[24,24]})}):L.circleMarker([p.lat,p.lon],{radius:3,color:'#236d50'});
   marker.on('click',(ev)=>{const e=ev as L.LeafletMouseEvent;L.DomEvent.stopPropagation(e.originalEvent);if(tool!=='select')return;if(!e.originalEvent.ctrlKey&&!e.originalEvent.metaKey)selected.clear();if(selected.has(i))selected.delete(i);else selected.add(i);shapeIndex=-1;tab='points';renderPanel();renderMap();});
   marker.on('dragstart',()=>stamp()).on('dragend',e=>{const c=(e.target as L.Marker).getLatLng();p.lon=c.lng;p.lat=c.lat;invalidateTerrain();void changed();});marker.addTo(routeLayer);
  });
 }
 if(m.home)L.marker(latlng(m.home),{draggable:tool==='select',icon:L.divIcon({className:'home-pin',html:'H',iconSize:[28,28]})}).on('dragstart',()=>stamp()).on('dragend',e=>{const c=(e.target as L.Marker).getLatLng();m.home=[c.lng,c.lat];invalidateTerrain();void changed();}).addTo(shapesLayer);
 renderHelp();
}
function field(label:string,key:string,hint='',unitField=false){const val=m.settings[key];return `<label class="field">${esc(label)}<input data-setting="${key}" type="number" step="any" value="${esc(typeof val==='number'&&unitField?+(val*factor()).toFixed(2):val)}" ${unitField?'data-unit="true"':''}>${hint?`<small>${esc(hint)}</small>`:''}</label>`;}
function check(label:string,key:string){return `<label class="check"><input type="checkbox" data-setting="${key}" ${m.settings[key]?'checked':''}>${esc(label)}</label>`;}
function select(label:string,key:string,options:[string,string][]){return `<label class="field">${esc(label)}<select data-setting="${key}">${options.map(([v,l])=>`<option value="${v}" ${m.settings[key]===v?'selected':''}>${l}</option>`).join('')}</select></label>`;}
const cameraOptions:[string,string][]=[['takePhoto','Take photo'],['none','No action / manual timed shots'],['startRecord','Start recording'],['stopRecord','Stop recording']];
function renderPanel(){
 const oldOpen=renderedTab===tab?[...document.querySelectorAll<HTMLDetailsElement>('#panel details[open]')].map(d=>d.querySelector('summary')?.textContent):[];const oldScroll=renderedTab===tab?$('panel').scrollTop:0;renderedTab=tab;
 document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
 let html='';
 if(tab==='plan'){
 html=`<div class="eyebrow">01 / Shape the mission</div><h2>What are you mapping?</h2><p>Draw a boundary on the map. Set your flight height and image coverage, then generate a route.</p>
 <div class="section"><label class="field">Mission pattern<select id="mode"><option value="survey" ${m.mode==='survey'?'selected':''}>Area survey</option><option value="corridor" ${m.mode==='corridor'?'selected':''}>Corridor survey</option><option value="orbit" ${m.mode==='orbit'?'selected':''}>Orbit / point of interest</option><option value="manual" ${m.mode==='manual'?'selected':''}>Manual waypoints</option></select></label>
 <div class="grid">${field('Height above takeoff · '+unit,'altitude','Use terrain following for height above ground.',true)}${field('Speed · '+unit+'/s','speed','',true)}</div>
 <label class="field">Display units<select id="units"><option value="m" ${unit==='m'?'selected':''}>Meters</option><option value="ft" ${unit==='ft'?'selected':''}>Feet</option></select></label>
 ${m.mode==='orbit'?`<div class="grid">${field('Orbit radius · '+unit,'radius','',true)}${field('Points per orbit','orbitPoints')}</div><button class="wide" id="place-poi">Place orbit center</button>`:''}
 ${m.mode==='corridor'?field('Corridor width · '+unit,'corridorWidth','Draw its centerline with the Corridor tool.',true):''}
 ${m.mode==='manual'?'<button id="add-manual" class="wide">Add waypoints on map</button>':`<button id="generate" class="primary wide">Generate flight path</button>`}
 <div class="subtle">${m.shapes.length} drawn shapes · ${m.home?'Takeoff point set':'Takeoff point not set'}</div></div>
 <div class="section"><h3>Image coverage</h3><div class="grid">${field('Front overlap · %','frontOverlap')}${field('Side overlap · %','sideOverlap')}</div>${check('Photo at each capture position','dense')}${check('Crosshatch: add a second grid at 90°','crosshatch')}
 <div class="hint">${report?`Approx. ${report.footprint.gsd.toFixed(2)} cm / pixel · ${heightLabel(report.footprint.spacing)} between legs`:'Coverage uses your camera dimensions below.'}<br>Calculated for a nadir camera on level ground.</div></div>
 <details><summary>Flight direction & geometry</summary><div>${check('Choose direction along the longest boundary edge','autoAngle')}${field('Grid angle · degrees, 0 = east–west','angle')}${field('Override spacing · '+unit,'spacing','0 uses overlap-based spacing.',true)}${check('Straight legs with stops at waypoints','straight')}<button id="reverse" class="wide">Reverse waypoint order</button></div></details>
 <details><summary>Camera & actions</summary><div>${field('Gimbal pitch · degrees','gimbal','−90 looks straight down. 0 faces the horizon.')}${select('Action at each generated waypoint','action',cameraOptions)}${field('Minimum camera interval · seconds','interval')}
 <div class="grid">${field('Sensor width · mm','sensorWidth')}${field('Sensor height · mm','sensorHeight')}${field('Actual focal length · mm','focalLength')}${field('Image width · pixels','imageWidth')}</div><div class="subtle">Camera dimensions are editable planning assumptions. Enter your camera’s actual values for meaningful GSD and overlap estimates.</div>${check('Add nadir reference windows along photo legs','referenceWindows')}<p>Reference windows hold the camera down near each leg midpoint. No GPS accuracy improvement is assumed.</p><button id="apply-camera" class="wide">Apply camera & speed to existing points</button></div></details>
 <details><summary>Terrain following</summary><div><p>Set takeoff on the map first. ODP samples the route every 30 m or less, then adjusts heights relative to that point.</p>${field('Minimum ground clearance · '+unit,'clearance','',true)}${field('Maximum altitude above takeoff · '+unit,'maxAltitude','Your project limit, not an airspace authorization.',true)}<button id="terrain-usgs" class="wide">Load USGS terrain · United States</button><button id="terrain-local" class="wide" style="margin-top:8px">Use local elevation GeoTIFF</button><div class="subtle">USGS requests send route coordinates to USGS. Local GeoTIFF sampling stays on this computer. Raster elevations must be meters.</div>${m.terrainSource?`<div class="hint">${esc(m.terrainSource)}</div><button id="terrain-clear">Return to constant height</button>`:''}</div></details>
 <details><summary>Presets</summary><div><label class="field">Preset name<input id="preset-name" placeholder="e.g. Detailed roof survey"></label><button id="preset-save" class="wide">Save these settings as a preset</button></div></details>`;
 if(shapeIndex>=0){html+=`<div class="section"><h3>Selected ${esc(m.shapes[shapeIndex].kind)}</h3><p>Drag its corner handles on the map. Regenerate to update the flight route.</p><button id="delete-shape" class="danger wide">Remove selected shape</button></div>`;}
 }
 if(tab==='points'){
 const p=selected.size===1?m.points[[...selected][0]]:null;
 html=`<div class="eyebrow">02 / Refine the route</div><h2>Every point, in reach.</h2><p>Click a waypoint on the map or below. Drag it to move it. Ctrl-click selects a group.</p><div class="row"><button id="select-all">Select all</button><button id="reverse">Reverse route</button></div><div class="row" style="margin-top:8px"><button id="add-manual">Add points</button><button id="clear-selection">Clear selection</button></div>`;
 if(selected.size){html+=`<div class="section"><h3>${p?'Waypoint '+([...selected][0]+1):selected.size+' waypoints selected'}</h3><div class="grid">${p?`<label class="field">Latitude<input id="point-lat" type="number" step="any" value="${p.lat}"></label><label class="field">Longitude<input id="point-lon" type="number" step="any" value="${p.lon}"></label>`:''}<label class="field">Height · ${unit}<input id="point-alt" type="number" step="any" value="${p?p.alt*factor():''}" placeholder="Keep current"></label><label class="field">Speed · ${unit}/s<input id="point-speed" type="number" step="any" value="${p?p.speed*factor():''}" placeholder="Keep current"></label><label class="field">Gimbal · degrees<input id="point-gimbal" type="number" value="${p?p.gimbal:''}" placeholder="Keep current"></label><label class="field">Hover · seconds<input id="point-hover" type="number" value="${p?p.hover:''}" placeholder="Keep current"></label><label class="field">Heading · degrees<input id="point-heading" type="number" value="${p?.heading??''}" placeholder="Follow route"></label></div><label class="field">Camera action<select id="point-action"><option value="">Keep current</option>${cameraOptions.map(([v,l])=>`<option value="${v}" ${p?.action===v?'selected':''}>${l}</option>`).join('')}</select></label><div class="row"><button id="apply-point" class="primary">Apply edits</button><button id="delete-points" class="danger">Delete selected</button></div>${p?'<div class="row" style="margin-top:8px"><button id="point-up">Move earlier</button><button id="point-down">Move later</button><button id="point-duplicate">Duplicate</button></div>':''}<button id="clear-unsupported" class="wide" style="margin-top:8px">Clear unsupported imported actions</button></div>`;}
 html+=`<div class="wp-list" aria-label="Waypoint list">${m.points.map((p,i)=>`<button class="wp-row ${selected.has(i)?'active':''}" data-point="${i}"><b>${String(i+1).padStart(2,'0')}</b><span>${heightLabel(p.alt)} · ${esc(p.action==='takePhoto'?'Photo':p.action==='none'?'Transit':p.action)}</span>${p.unsupported?'<span class="danger">!</span>':''}</button>`).join('')}</div>${!m.points.length?'<div class="hint">Generate a route, import a KMZ, or add waypoints on the map.</div>':''}`;
 }
 if(tab==='review'){
 html=`<div class="eyebrow">03 / Check & take it with you</div><h2>Review before flight.</h2><p>Check the route here, then open the exported flight in DJI Fly to verify aircraft acceptance and flight settings.</p><div class="section"><span class="pill">${esc(m.profile?.name||'Aircraft profile needed')}</span><div class="subtle">${m.profile?'Profile taken from an imported DJI mission.':'Import a known-good DJI KMZ to identify your aircraft. Your current route will stay open.'}</div><button id="profile-import" class="wide">${m.profile?'Change':'Load'} aircraft profile from KMZ</button>${select('At mission completion','finish',[['goHome','Return to home'],['noAction','Hover'],['autoLand','Land at last waypoint'],['gotoFirstWaypoint','Return to first waypoint']])}${select('If controller signal is lost','lost',[['goBack','Return to home'],['hover','Hover'],['landing','Land']])}</div>
 ${m.heightMode!=='relativeToStartPoint'?`<div class="hint warn">This mission uses ${esc(m.heightMode)} heights.</div><label class="field">Takeoff elevation in the same vertical datum · meters<input id="absolute-home" type="number" step="any"></label><button id="convert-heights" class="wide">Convert to takeoff-relative heights</button>`:''}
 ${m.importNotes?.map(note=>`<div class="hint">${esc(note)}</div>`).join('')||''}
 ${report?report.errors.map(e=>`<div class="hint error">${esc(e)}</div>`).join(''):'<div class="hint">Checking route…</div>'}
 ${report&&!report.errors.length?'<div class="hint">Geometry and file checks are clear. Complete the field checks below before flying.</div>':''}
 <div class="section"><h3>Battery & export</h3><div class="grid">${field('Battery · minutes','batteryMinutes')}${field('Reserve · %','reserve')}${field('Waypoints per flight','maxPoints')}</div><p>Includes return transit when takeoff is set. Wind, acceleration and aircraft performance can change duration.</p><button id="export-kmz" class="primary wide" ${report?.errors.length?'disabled':''}>Export DJI KMZ</button><button id="export-split" class="wide" style="margin-top:8px" ${report?.errors.length?'disabled':''}>Split into battery-sized flights</button></div>
 <details open><summary>Field checks & assumptions</summary><div>${report?.warnings.map(w=>`<div class="subtle">• ${esc(w)}</div>`).join('')||''}<label class="check"><input type="checkbox">Airspace, site permission and weather checked</label><label class="check"><input type="checkbox">Trees, wires, people and takeoff clearance checked</label><label class="check"><input type="checkbox">Route, heights, camera and end action checked in DJI Fly</label></div></details>
 <details><summary>Connected controller</summary><div><p>Replaces the remembered DJI Fly slot, after making a backup. Keep USB connected until readback completes.</p><button id="controller" class="wide">Check connected controller</button><div id="controller-status" class="subtle"></div><button id="send-plan" class="primary wide" style="margin-top:8px" ${report?.errors.length?'disabled':''}>Send this planned mission</button>${m.sourceOriginal?'<button id="send-original" class="wide" style="margin-top:8px">Send original imported KMZ unchanged</button>':''}<button id="restore" class="wide" style="margin-top:8px">Restore original controller flight</button><button id="reset-slot" class="wide" style="margin-top:8px">Choose another saved slot next time</button></div></details>
 <details><summary>Other export formats</summary><div class="grid"><button id="export-project">ODP project</button><button id="export-geojson">GeoJSON</button><button id="export-csv">Waypoint CSV</button><button id="export-kml">Route KML</button><button id="print">Field brief</button></div></details>`;
 }
 if(tab==='library'){
 html=`<div class="eyebrow">Local mission library</div><h2>Pick up where you left off.</h2><p>Missions and presets are saved on this computer. Export an ODP project to move a mission elsewhere.</p><button id="save-library" class="primary wide">Save current mission</button><div class="section"><h3>Saved missions · ${library.missions.length}</h3>${library.missions.map(x=>`<div class="card"><b>${esc(x.name)}</b><small>${x.points.length} waypoints · ${x.shapes.length} shapes</small><div class="row"><button data-load="${x.id}">Open mission</button><button data-archive="${x.id}">Archive</button></div></div>`).join('')||'<div class="hint">Your saved missions will appear here.</div>'}</div><div class="section"><h3>Settings presets</h3>${library.presets.map(x=>`<div class="card"><b>${esc(x.name)}</b><small>${heightLabel(Number(x.settings.altitude))} · ${x.settings.frontOverlap}% overlap</small><div class="row"><button data-preset="${x.id}">Apply settings</button><button data-archive-preset="${x.id}">Archive</button></div></div>`).join('')||'<p>Save a preset under Plan to reuse camera and flight settings.</p>'}</div>`;
 }
 $('panel').innerHTML=html;for(const d of document.querySelectorAll<HTMLDetailsElement>('#panel details'))if(oldOpen.includes(d.querySelector('summary')?.textContent))d.open=true;$('panel').scrollTop=oldScroll;bindPanel();
}
function bind(id:string,fn:()=>void|Promise<void>){$(id)?.addEventListener('click',handle(fn));}
function bindPanel(){
 document.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-setting]').forEach(el=>el.addEventListener('change',()=>{
  stamp();const key=el.dataset.setting!;m.settings[key]=el instanceof HTMLInputElement&&el.type==='checkbox'?el.checked:el instanceof HTMLInputElement?Number(el.value)/(el.dataset.unit?factor():1):el.value;void changed(false);
 }));
 $('mode')?.addEventListener('change',()=>{stamp();m.mode=$<HTMLSelectElement>('mode').value;renderPanel();setTool(m.mode==='orbit'?'poi':m.mode==='corridor'?'corridor':m.mode==='manual'?'waypoint':'area');persist();});
 $('units')?.addEventListener('change',()=>{unit=$<HTMLSelectElement>('units').value;localStorage.setItem('odp-units',unit);renderPanel();renderStats();});
 bind('generate',async()=>{const button=$('generate');button.classList.add('busy');try{const next=await api<Mission>('generate',{mission:m});stamp();m=next;selected.clear();tab='points';await changed();fit();toast(`Generated ${m.points.length} waypoints. Review the route and camera settings.`);}finally{button.classList.remove('busy');}});
 bind('place-poi',()=>setTool('poi'));bind('add-manual',()=>setTool('waypoint'));
 bind('reverse',()=>{stamp();m.points.reverse();selected.clear();void changed();});
 bind('apply-camera',()=>{stamp();for(const p of m.points){p.speed=numeric('speed');p.gimbal=numeric('gimbal');delete p.gimbalEnd;p.action=String(m.settings.action);}void changed();toast('Applied camera and speed to the existing route.');});
 bind('terrain-usgs',()=>loadTerrain('usgs'));bind('terrain-local',()=>$('dem').click());
 bind('terrain-clear',()=>{stamp();invalidateTerrain();for(const p of m.points)p.alt=numeric('altitude');void changed();});
 bind('preset-save',async()=>{const name=$<HTMLInputElement>('preset-name').value.trim();if(!name)throw new Error('Enter a preset name.');await api('save',{kind:'presets',value:{name,settings:m.settings}});await refreshLibrary();toast('Preset saved.');});
 bind('delete-shape',()=>{stamp();m.shapes.splice(shapeIndex,1);shapeIndex=-1;void changed();});
 bind('select-all',()=>{selected=new Set(m.points.map((_,i)=>i));renderPanel();renderMap();});
 bind('clear-selection',()=>{selected.clear();renderPanel();renderMap();});
 document.querySelectorAll<HTMLButtonElement>('[data-point]').forEach(b=>b.addEventListener('click',e=>{const i=Number(b.dataset.point);if(!e.ctrlKey&&!e.metaKey)selected.clear();if(selected.has(i))selected.delete(i);else selected.add(i);renderPanel();renderMap();map.panTo([m.points[i].lat,m.points[i].lon]);}));
 bind('apply-point',()=>{
  stamp();const changes:Partial<Waypoint>={};
  for(const key of ['lat','lon','alt','speed','gimbal','hover','heading'] as const){const input=$<HTMLInputElement>('point-'+key);if(input&&input.value!=='')changes[key]=Number(input.value)/(['alt','speed'].includes(key)?factor():1);}
  const act=$<HTMLSelectElement>('point-action').value;if(act)changes.action=act;if(selected.size===1&&$<HTMLInputElement>('point-heading').value==='')changes.heading=null;
  for(const i of selected){Object.assign(m.points[i],changes);if('gimbal' in changes)delete m.points[i].gimbalEnd;}
  if('lat' in changes||'lon' in changes)invalidateTerrain();void changed();
 });
 bind('delete-points',()=>{stamp();m.points=m.points.filter((_,i)=>!selected.has(i));selected.clear();void changed();});
 bind('clear-unsupported',async()=>{if(!await confirmDialog('Clear unsupported actions?','This removes actions the editor cannot preserve from the selected points. The original imported KMZ remains available for unchanged transfer.','Clear actions'))return;stamp();for(const i of selected)delete m.points[i].unsupported;void changed();});
 for(const [id,delta] of [['point-up',-1],['point-down',1]] as const)bind(id,()=>{const i=[...selected][0],j=i+delta;if(j<0||j>=m.points.length)return;stamp();[m.points[i],m.points[j]]=[m.points[j],m.points[i]];selected=new Set([j]);void changed();});
 bind('point-duplicate',()=>{const i=[...selected][0];stamp();m.points.splice(i+1,0,clone(m.points[i]));selected=new Set([i+1]);void changed();});
 bind('profile-import',()=>$('profile-file').click());
 bind('convert-heights',()=>{const input=$<HTMLInputElement>('absolute-home');if(!input.value||!Number.isFinite(Number(input.value)))throw new Error('Enter a known takeoff elevation in the same vertical datum as the imported mission.');stamp();for(const p of m.points)p.alt-=Number(input.value);m.heightMode='relativeToStartPoint';invalidateTerrain();void changed();});
 bind('export-kmz',()=>exportFlight('kmz'));bind('export-split',()=>exportFlight('split'));
 bind('export-project',()=>download(JSON.stringify(m,null,2),m.name+'.odp.json','application/json'));
 bind('export-geojson',()=>download(JSON.stringify(geojson(),null,2),m.name+'.geojson','application/geo+json'));
 bind('export-csv',()=>{const keys=['index','latitude','longitude','height_relative_to_takeoff_m','speed_m_s','gimbal_deg','heading_deg','action','hover_s'];const rows=m.points.map((p,i)=>[i+1,p.lat,p.lon,p.alt,p.speed,p.gimbal,p.heading??'',p.action,p.hover]);download([keys,...rows].map(r=>r.join(',')).join('\n'),m.name+'.csv','text/csv');});
 bind('export-kml',()=>{const coords=m.points.map(p=>`${p.lon},${p.lat},${p.alt}`).join(' ');download(`<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>${esc(m.name)}</name><description>ODP route reference. Heights are relative to takeoff; displayed clamped to ground to avoid a false vertical datum.</description><Placemark><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>${coords}</coordinates></LineString></Placemark></Document></kml>`,m.name+'.kml','application/vnd.google-earth.kml+xml');});
 bind('print',printBrief);
 bind('controller',async()=>{const result=await job<{slots:{device:string;folder:string}[]}>('controller',{},'Looking for your DJI controller…');$('controller-status').textContent=result.slots.length?`${result.slots[0].device} · ${result.slots.length} saved slots found`:'No saved flight found. Unlock the controller, choose USB file transfer and save a placeholder flight in DJI Fly.';});
 bind('send-plan',()=>send(false));bind('send-original',()=>send(true));
 bind('restore',async()=>{if(await confirmDialog('Restore the controller backup?','This replaces the saved controller flight with its backed-up original.','Restore backup')){await job('restore',{},'Restoring the original controller flight…');toast('Controller backup restored.');}});
 bind('reset-slot',async()=>{if(await confirmDialog('Choose another slot?','The next transfer may replace any available saved flight on the connected controller.','Reset slot choice')){await api('reset-slot',{});toast('Slot choice reset.');}});
 bind('save-library',save);
 document.querySelectorAll<HTMLButtonElement>('[data-load]').forEach(b=>b.addEventListener('click',()=>{const mission=library.missions.find(v=>v.id===b.dataset.load)!;loadMission(mission,mission.id);tab='points';renderPanel();toast('Mission opened.');}));
 document.querySelectorAll<HTMLButtonElement>('[data-preset]').forEach(b=>b.addEventListener('click',()=>{stamp();m.settings=clone(library.presets.find(v=>v.id===b.dataset.preset)!.settings);tab='plan';void changed();toast('Preset applied. Regenerate to update the route.');}));
 for(const kind of ['missions','presets'] as const){const attr=kind==='missions'?'data-archive':'data-archive-preset';document.querySelectorAll<HTMLButtonElement>('['+attr+']').forEach(b=>b.addEventListener('click',handle(async()=>{await api('archive',{kind,id:b.getAttribute(attr)});await refreshLibrary();renderPanel();toast('Archived locally.');})));}
}
async function loadTerrain(source:string){const initial=JSON.stringify(m);const result=await job<Mission>('terrain',{mission:m,source},'Sampling ground elevation and adjusting route heights…');if(JSON.stringify(m)!==initial)throw new Error('The mission changed during terrain sampling. Load terrain again for the current route.');stamp();m=result;await changed();toast('Terrain loaded. Review the altitude profile and ceiling checks.');}
async function exportFlight(format:'kmz'|'split'){const result=await api<{data:string;extension:string}>('export',{mission:m,format});download(decode(result.data),m.name+'.'+result.extension,'application/octet-stream');toast(format==='split'?'Separate flight KMZs exported in a ZIP.':'DJI KMZ exported. Open it in DJI Fly before flight.');}
async function send(original:boolean){if(!await confirmDialog('Replace the saved controller flight?',original?'Send the original imported KMZ byte for byte. The controller flight will be backed up first.':'Send the planned mission shown here. The controller flight will be backed up first. Verify the new route in DJI Fly before flight.','Back up & send'))return;const result=await job<{status:string;waypoints:number}>('transfer',{mission:m,original},'Backing up, copying and reading the controller file back… Keep USB connected.');toast(result.status==='unchanged'?'The controller already contains this exact KMZ.':`Transferred and read back successfully · ${result.waypoints} waypoints.`);}
async function save(){m.name=$<HTMLInputElement>('mission-name').value.trim()||'Untitled mission';const result=await api<{id:string}>('save',{id:savedId,value:m});savedId=result.id;m.id=result.id;await refreshLibrary();if(tab==='library')renderPanel();persist();toast('Mission saved to your local library.');}
async function refreshLibrary(){library=await api<Library>('library');}
function download(data:BlobPart,name:string,type:string){const blob=new Blob([data],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name.replace(/[\\/:*?"<>|]/g,'-');a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function decode(s:string):Uint8Array<ArrayBuffer>{return Uint8Array.from(atob(s),c=>c.charCodeAt(0));}
async function encode(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Could not read the file.'));reader.readAsDataURL(file);});}
async function importMission(file:File){if(file.size>20*1024*1024)throw new Error('Import must be under 20 MB.');const next=await api<Mission>('import',{name:file.name.endsWith('.geojson')?file.name+'.json':file.name,data:await encode(file)});if(!next.profile)next.profile=clone(profile);else profile=next.profile;loadMission(next);tab=next.points.length?'points':'plan';renderPanel();toast(`Imported ${next.points.length} waypoints and ${next.shapes.length} shapes. Nothing sent to the controller.`);}
function geojson(){return {type:'FeatureCollection',features:[...m.shapes.map(s=>({type:'Feature',properties:{role:s.kind},geometry:s.kind==='poi'?{type:'Point',coordinates:s.coords[0]}:s.kind==='corridor'?{type:'LineString',coordinates:s.coords}:{type:'Polygon',coordinates:[[...s.coords,s.coords[0]]]}})),...m.points.map((p,i)=>({type:'Feature',properties:{index:i,...p},geometry:{type:'Point',coordinates:[p.lon,p.lat,p.alt]}}))]};}
function renderStats(){const r=report;$('stats').innerHTML=[['Flight distance',r?distanceLabel(r.distance):'—'],['Est. flight time',r?Math.ceil(r.seconds/60)+' <small>min</small>':'—'],['Waypoints',String(m.points.length)],['Photo positions',r?String(r.photoCount):'—'],['Ground resolution',r?r.footprint.gsd.toFixed(1)+' <small>cm/px</small>':'—']].map(([label,value])=>`<div class="stat"><span>${label}</span><b>${value}</b></div>`).join('');
 const ps=m.points;$('profile-empty').classList.toggle('hidden',ps.length>0);$('profile-source').textContent=m.terrainSource||'Terrain not loaded';if(!ps.length){$('profile').innerHTML='';return;}
 const grounds=ps.map(p=>p.ground===null?null:p.ground-Number(m.settings.homeElevation));const values=[0,...ps.map(p=>p.alt),...grounds.filter((x):x is number=>x!==null)];const low=Math.min(...values),high=Math.max(...values,low+10);const distances=[0];for(let i=1;i<ps.length;i++)distances.push(distances[i-1]+L.latLng(ps[i-1].lat,ps[i-1].lon).distanceTo([ps[i].lat,ps[i].lon]));const max=distances.at(-1)||1;const xy=(value:number,i:number)=>`${35+distances[i]/max*925},${60-(value-low)/(high-low)*50}`;
 $('profile').setAttribute('viewBox','0 0 1000 70');$('profile').innerHTML=`<line x1="35" y1="60" x2="970" y2="60" stroke="#d6e1d7"/><text x="0" y="12" font-size="10" fill="#7d8e81">${heightLabel(high)}</text><text x="0" y="61" font-size="10" fill="#7d8e81">${heightLabel(low)}</text>${grounds.every(g=>g!==null)?`<polygon points="35,65 ${grounds.map((g,i)=>xy(g!,i)).join(' ')} 960,65" fill="#dfd7be"/><polyline points="${grounds.map((g,i)=>xy(g!,i)).join(' ')}" fill="none" stroke="#a49674" stroke-width="1"/>`:''}<polyline points="${ps.map((p,i)=>xy(p.alt,i)).join(' ')}" fill="none" stroke="#2a7757" stroke-width="2"/>`;
}
function stopSimulation(){if(simTimer){clearInterval(simTimer);simTimer=null;}simMarker?.remove();simMarker=null;$('simulate').textContent='▶ Preview';}
function simulate(){if(simTimer){stopSimulation();return;}if(m.points.length<2){toast('Add a route to preview.',true);return;}let i=0,t=0;simMarker=L.marker([m.points[0].lat,m.points[0].lon],{icon:L.divIcon({className:'sim-pin',html:'✦',iconSize:[25,25]})}).addTo(map);$('simulate').textContent='■ Stop preview';toast('Route preview at 20× speed. This is a path animation, not a flight dynamics simulation.');simTimer=setInterval(()=>{if(i>=m.points.length-1){stopSimulation();return;}const a=m.points[i],b=m.points[i+1];const duration=Math.max(.1,L.latLng(a.lat,a.lon).distanceTo([b.lat,b.lon])/a.speed);t+=2/duration;if(t>=1){i++;t=0;}simMarker?.setLatLng([a.lat+(b.lat-a.lat)*Math.min(t,1),a.lon+(b.lon-a.lon)*Math.min(t,1)]);},100);}
function showDialog(title:string,body:string){$('dialog').innerHTML=`<h2>${esc(title)}</h2>${body}<div class="dialog-actions"><button id="dialog-close">Close</button></div>`;$('dialog-close').onclick=()=>($('dialog') as HTMLDialogElement).close();($('dialog') as HTMLDialogElement).showModal();}
async function confirmDialog(title:string,message:string,action:string){return new Promise<boolean>(resolve=>{const d=$<HTMLDialogElement>('dialog');d.innerHTML=`<h2>${esc(title)}</h2><p>${esc(message)}</p><div class="dialog-actions"><button id="confirm-no">Cancel</button><button id="confirm-yes" class="primary">${esc(action)}</button></div>`;const finish=(answer:boolean)=>{d.close();resolve(answer);};$('confirm-no').onclick=()=>finish(false);$('confirm-yes').onclick=()=>finish(true);d.oncancel=()=>resolve(false);d.showModal();});}
function printBrief(){document.querySelector('.brief')?.remove();const el=document.createElement('article');el.className='brief';el.innerHTML=`<h1>${esc(m.name)}</h1><p>OpenDronePlanner field brief · ${new Date().toLocaleString()}</p><p>Aircraft: ${esc(m.profile?.name||'Unspecified')}<br>${m.points.length} waypoints · ${report?distanceLabel(report.distance):'Unknown distance'} · ${report?Math.ceil(report.seconds/60):'?'} estimated minutes<br>Finish: ${esc(m.settings.finish)} · Signal loss: ${esc(m.settings.lost)}<br>Terrain: ${esc(m.terrainSource||'Not loaded')}<br>Heights are meters relative to takeoff.</p><p>${report?.errors.map(esc).join('<br>')||''}</p><p>${report?.warnings.map(esc).join('<br>')||''}</p><p>□ Airspace and weather reviewed　 □ Obstacles checked　 □ DJI Fly route reviewed　 □ Batteries checked</p><table><thead><tr><th>Point</th><th>Latitude</th><th>Longitude</th><th>Height m</th><th>Speed m/s</th><th>Gimbal</th><th>Action</th></tr></thead><tbody>${m.points.map((p,i)=>`<tr><td>${i+1}</td><td>${p.lat.toFixed(7)}</td><td>${p.lon.toFixed(7)}</td><td>${p.alt.toFixed(1)}</td><td>${p.speed}</td><td>${p.gimbal}</td><td>${esc(p.action)}</td></tr>`).join('')}</tbody></table>`;document.body.append(el);window.print();}
function undo(){if(!history.length)return;future.push(clone(m));m=history.pop()!;selected.clear();shapeIndex=-1;$<HTMLInputElement>('mission-name').value=m.name;void changed();}
function redo(){if(!future.length)return;history.push(clone(m));m=future.pop()!;selected.clear();shapeIndex=-1;$<HTMLInputElement>('mission-name').value=m.name;void changed();}
for(const b of document.querySelectorAll<HTMLButtonElement>('[data-tab]'))b.addEventListener('click',handle(async()=>{tab=b.dataset.tab!;if(tab==='library')await refreshLibrary();renderPanel();}));
for(const b of document.querySelectorAll<HTMLButtonElement>('[data-tool]'))b.addEventListener('click',()=>{setTool(b.dataset.tool!);$('sidebar').classList.remove('open');});
bind('undo',undo);bind('redo',redo);bind('fit',fit);bind('simulate',simulate);bind('save',save);bind('import',()=>$('file').click());
bind('new',async()=>{await save();loadMission(base());tab='plan';renderPanel();toast('Started a new mission. The previous mission is in your library.');});
bind('top-review',()=>{tab='review';renderPanel();$('sidebar').classList.add('open');});bind('mobile',()=>{$('sidebar').classList.toggle('open');});
bind('help',()=>showDialog('A clearer route from map to flight',`<p><b>1. Plan.</b> Import an existing DJI KMZ or draw a survey boundary. Add a takeoff point. Enter your altitude, speed and camera dimensions, then generate.</p><p><b>2. Refine.</b> Drag waypoints, change individual or grouped actions, reverse the route, or load ground terrain from USGS or a local GeoTIFF.</p><p><b>3. Review.</b> Resolve the red checks, choose end and signal-loss actions, then export or send to the controller. Open the saved flight in DJI Fly before flying.</p><p><b>Keyboard.</b> Ctrl+Z undo, Ctrl+Shift+Z redo, Ctrl+S save, Ctrl+A selects all waypoints when focus is on the map. Escape cancels drawing. Ctrl-click toggles waypoint selection.</p><p><b>Local by default.</b> Mission files and presets stay on this computer. Background maps contact their tile provider. Place search contacts OpenStreetMap Nominatim; the USGS terrain button sends route coordinates to USGS.</p><p>Existing KMZ files can still be dropped into the separate Waypoint Transfer utility for immediate unchanged USB installation. A drop in this planner imports for editing.</p>`));
$('mission-name').addEventListener('change',()=>{stamp();m.name=$<HTMLInputElement>('mission-name').value||'Untitled mission';persist();});
$('file').addEventListener('change',handle(async()=>{const input=$<HTMLInputElement>('file');if(input.files?.[0])await importMission(input.files[0]);input.value='';}));
$('profile-file').addEventListener('change',handle(async()=>{const input=$<HTMLInputElement>('profile-file');const file=input.files?.[0];if(!file)return;const imported=await api<Mission>('import',{name:file.name,data:await encode(file)});if(!imported.profile)throw new Error('This KMZ has no DJI aircraft profile.');stamp();m.profile=imported.profile;profile=imported.profile;input.value='';await changed();toast('Aircraft profile loaded. Your planned route is unchanged.');}));
$('dem').addEventListener('change',handle(async()=>{const file=$<HTMLInputElement>('dem').files?.[0];if(!file)return;if(file.size>28*1024*1024)throw new Error('Crop the elevation raster to less than 28 MB.');const result=await api<{id:string}>('terrain-file',{name:file.name,data:await encode(file)});await loadTerrain(result.id);$<HTMLInputElement>('dem').value='';}));
let dragDepth=0;window.addEventListener('dragenter',e=>{if(e.dataTransfer?.types.includes('Files')){e.preventDefault();dragDepth++;$('drop-overlay').classList.remove('hidden');}});window.addEventListener('dragleave',()=>{if(--dragDepth<=0)$('drop-overlay').classList.add('hidden');});window.addEventListener('dragover',e=>{if(e.dataTransfer?.types.includes('Files')){e.preventDefault();e.dataTransfer.dropEffect='copy';}});window.addEventListener('drop',e=>{e.preventDefault();dragDepth=0;$('drop-overlay').classList.add('hidden');const file=e.dataTransfer?.files[0];if(file)void importMission(file).catch(err=>toast(err.message,true));});
window.addEventListener('keydown',e=>{const editing=(e.target as HTMLElement).matches('input,textarea,select');if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();void save().catch(err=>toast(err.message,true));}if(editing)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='a'){e.preventDefault();selected=new Set(m.points.map((_,i)=>i));tab='points';renderPanel();renderMap();}if(e.key==='Escape')setTool('select');});
$('search-form').addEventListener('submit',e=>{e.preventDefault();void (async()=>{const query=$<HTMLInputElement>('search').value.trim();if(!query)return;const values=query.split(',').map(Number);if(values.length===2&&values.every(Number.isFinite)&&Math.abs(values[0])<=85&&Math.abs(values[1])<=180){map.setView([values[0],values[1]],17);return;}const results=await job<{display_name:string;lat:string;lon:string}[]>('search',{query},'Searching places…');$('search-results').innerHTML=results.map((r,i)=>`<button data-search-result="${i}">${esc(r.display_name)}</button>`).join('');if(!results.length)toast('No matching place found. Try latitude, longitude.');document.querySelectorAll<HTMLButtonElement>('[data-search-result]').forEach(b=>b.onclick=()=>{const result=results[Number(b.dataset.searchResult)];map.setView([Number(result.lat),Number(result.lon)],16);$('search-results').innerHTML='';});})().catch(err=>toast(err.message,true));});
async function init(){const status=await api<{defaults:Settings;offline:boolean}>('status');defaults=status.defaults;profile=await api<Profile|null>('profile');m=base();const serverDraft=await api<Mission|null>('draft');const draft=serverDraft?JSON.stringify(serverDraft):localStorage.getItem('odp-draft');if(draft){try{const parsed=JSON.parse(draft);await api('review',{mission:parsed});m=parsed;}catch{toast('The saved browser draft could not be read. Your library is still available.',true);}}$<HTMLInputElement>('mission-name').value=m.name;savedId=m.id;tab=m.points.length?'points':'plan';await refreshLibrary();await changed();fit();if(status.offline)toast('Test session: controller access is disabled.');}
void init().catch(err=>{showDialog('Could not open the planner',`<p>${esc(err.message)}</p><p>Close and reopen OpenDronePlanner from its desktop icon.</p>`);});
