import './processing.css';
type FileRecord={name:string;size:number;sha256:string;kind:string;width?:number;height?:number;gps?:number[];camera?:string;metadataWarning?:string};
type Run={id:string;created:string;status:string;task?:string;project?:number;progress?:number;uploaded:number;total:number;mode:string;assets?:string[];error?:string;options:Record<string,unknown>};
type Capture={id:string;name:string;created:string;files:FileRecord[];runs:Run[];mission?:{name:string;points:unknown[]};notes:string;client:string;operator:string;findings:string;limitations:string};
type Engine={ready:boolean;busy:boolean;message:string;mode:string;threads:number;freeGB:number;presets:Record<string,{name:string;options:Record<string,unknown>}>};
type Option={name:string;type:string;domain?:unknown[];help?:string;value?:unknown};
type Api=<T>(path:string,body?:unknown)=>Promise<T>;
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const bytes=(n:number)=>n>1024**3?(n/1024**3).toFixed(2)+' GB':(n/1024**2).toFixed(1)+' MB';
export function mountProcessing(api:Api,getMission:()=>unknown,onPlan:(review:boolean)=>void){
 let captures:Capture[]=[],selected:Capture|null=null,engine:Engine|null=null,options:Option[]=[],busy=false,stage='media',poll:ReturnType<typeof setInterval>|null=null;
 const nav=document.createElement('nav');nav.className='workflow-nav';nav.setAttribute('aria-label','Drone workflow');nav.innerHTML='<button data-workflow="plan" class="active">1 · Plan flight</button><button data-workflow="fly">2 · Export & controller</button><button data-workflow="process">3 · Process & present</button>';
 document.querySelector('.topbar')!.after(nav);
 const root=document.createElement('section');root.className='processing-workspace hidden';root.id='processing-workspace';root.setAttribute('aria-label','Capture processing and presentation');document.querySelector('.workspace')!.after(root);
 const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
 const p=<T>(path:string,body?:unknown)=>api<T>('processing/'+path,body);
 function message(text:string,error=false){$('processing-message').textContent=text;$('processing-message').className=error?'processing-message error':'processing-message';}
 async function perform(fn:()=>Promise<void>){if(busy)return;busy=true;try{await fn();}catch(e){await refresh();message(e instanceof Error?e.message:String(e),true);}finally{busy=false;}}
 async function job<T>(path:string,body:unknown):Promise<T>{const {job}=await p<{job:string}>(path,body);for(;;){const r=await api<{done:boolean;result:T}>('job/'+job);if(r.done)return r.result;engine=await p<Engine>('status');$('engine-status').textContent=engine.message;await new Promise(r=>setTimeout(r,1000));}}
 async function refresh(){engine=await p<Engine>('status');captures=await p<Capture[]>('captures');if(selected)selected=captures.find(c=>c.id===selected!.id)||null;render();}
 async function openWeb(){const r=await p<{native:boolean;url:string}>('open',{});if(!r.native)window.open(r.url,'odp-webodm');}
 function chooseCapture(id:string){selected=captures.find(c=>c.id===id)||null;render();}
 function bind(id:string,fn:()=>Promise<void>){$(id)?.addEventListener('click',()=>void perform(fn));}
 function render(){
  root.innerHTML=`<aside class="capture-sidebar"><div class="capture-heading"><small>AFTER THE FLIGHT</small><h2>Capture library</h2><p>Keep the flight, original media, processing runs and delivery record together.</p></div><button id="capture-new" class="primary">+ Capture from current plan</button><button id="capture-unlinked">+ Capture without a plan</button><div class="capture-list">${captures.map(c=>`<button class="capture-card ${c.id===selected?.id?'active':''}" data-capture="${c.id}"><b>${esc(c.name)}</b><small>${new Date(c.created).toLocaleDateString()} · ${c.files.length} files</small><span>${esc(c.runs.at(-1)?.status||'Ready for media')}</span></button>`).join('')||'<p class="empty">No captures yet. Create one after a flight or import an existing photo survey.</p>'}</div><small>${engine?.freeGB??'…'} GB free on this computer</small></aside><main class="capture-main"><div class="processing-engine"><div><small>LOCAL PROCESSING ENGINE</small><p id="engine-status">${esc(engine?.message||'Checking engine…')}</p></div><div class="engine-actions"><label>Acceleration<select id="engine-mode" ${engine?.ready?'disabled':''}><option value="cpu">CPU · all computers</option><option value="cuda" ${engine?.mode!=='cpu'&&engine?.ready?'selected':''}>NVIDIA CUDA · optional</option></select></label><label>CPU threads<input id="engine-threads" type="number" min="1" max="128" value="${engine?.threads||8}" ${engine?.ready?'disabled':''}></label><button id="engine-start" ${engine?.ready?'disabled':''}>Start engine</button><button id="engine-stop" ${!engine?.ready?'disabled':''}>Stop</button><button id="webodm-open" class="primary" ${!engine?.ready?'disabled':''}>Full WebODM workspace ↗</button></div></div><div id="processing-message" class="processing-message" role="status"></div>${selected?detail():`<div class="capture-welcome"><div class="welcome-icon">◉</div><small>PLAN → FLY → PROCESS → PRESENT</small><h1>Turn your flight into useful work.</h1><p>Bring in photos, videos and field records. Reconstruct maps and models locally, inspect the results, then prepare a delivery packet with the original file manifest.</p><div class="welcome-features"><article><b>Maps and terrain</b><p>Orthomosaics, DSM, DTM, contours and GIS exports.</p></article><article><b>Models and measurements</b><p>Point clouds, textured 3D models, GCPs, profiles and volumes in WebODM.</p></article><article><b>A clear record</b><p>Flight links, file checksums, run options, reviewer findings and printable reports.</p></article></div><p class="subtle">Planning needs no processing engine. For reconstruction, install and start Docker once. ODP downloads the free engine on first use. No cloud account needed.</p></div>`}</main><input id="capture-files" type="file" multiple class="hidden" accept=".jpg,.jpeg,.png,.tif,.tiff,.dng,.mp4,.mov,.lrv,.ts,.srt,.txt,.csv,.json,.geojson,.kml,.kmz,.pdf"><input id="capture-folder" type="file" webkitdirectory multiple class="hidden">`;
  bind('capture-new',async()=>{selected=await p<Capture>('create',{name:(getMission() as {name:string}).name+' · capture',mission:getMission()});await refresh();});
  bind('capture-unlinked',async()=>{selected=await p<Capture>('create',{name:'Untitled capture'});await refresh();});
  root.querySelectorAll<HTMLButtonElement>('[data-capture]').forEach(b=>b.onclick=()=>chooseCapture(b.dataset.capture!));
  root.querySelectorAll<HTMLButtonElement>('[data-stage]').forEach(b=>b.onclick=()=>{stage=b.dataset.stage!;render();});
  bind('engine-start',async()=>{message('Starting the engine. Downloads can take several minutes.');await job('start',{mode:$<HTMLSelectElement>('engine-mode').value,threads:Number($<HTMLInputElement>('engine-threads').value)});await refresh();});
  bind('engine-stop',async()=>{message('Stopping processing services…');await job('stop',{});await refresh();});bind('webodm-open',openWeb);
  if(!selected)return;
  bind('capture-add',async()=>$<HTMLInputElement>('capture-files').click());bind('capture-add-folder',async()=>$<HTMLInputElement>('capture-folder').click());
  for(const id of ['capture-files','capture-folder'])$(id).onchange=()=>{const files=Array.from($<HTMLInputElement>(id).files||[]);void perform(()=>upload(files));};
  const drop=$('capture-drop');if(drop){drop.ondragover=e=>{e.preventDefault();e.stopPropagation();drop.classList.add('dragging');};drop.ondragleave=()=>drop.classList.remove('dragging');drop.ondrop=e=>{e.preventDefault();e.stopPropagation();drop.classList.remove('dragging');void perform(()=>upload(Array.from(e.dataTransfer?.files||[])));};}
  bind('processing-options',async()=>{const result=await p<Option[]|{options:Option[]}>('options');options=Array.isArray(result)?result:result.options;render();});
  $('option-search')?.addEventListener('input',()=>{const q=$<HTMLInputElement>('option-search').value.toLowerCase();root.querySelectorAll<HTMLElement>('[data-option-row]').forEach(el=>el.hidden=!el.textContent?.toLowerCase().includes(q));});
  root.querySelectorAll<HTMLButtonElement>('[data-add-option]').forEach(b=>b.onclick=()=>{const name=b.dataset.addOption!,o=options.find(x=>x.name===name)!;const input=$<HTMLTextAreaElement>('custom-options');try{const value=JSON.parse(input.value||'{}');value[name]=o.value??(o.type==='bool'?true:'');input.value=JSON.stringify(value,null,2);}catch{message('Custom options must be a JSON object.',true);}});
  bind('capture-process',async()=>{message('Verifying originals and uploading to WebODM…');const opts=JSON.parse($<HTMLTextAreaElement>('custom-options').value||'{}');if(!opts||Array.isArray(opts)||typeof opts!=='object')throw Error('Options must be an object.');selected=await job<Capture>('submit',{id:selected!.id,preset:$<HTMLSelectElement>('processing-preset').value,options:opts});stage='outputs';await refresh();});
  bind('capture-save-notes',async()=>{const body:Record<string,string>={id:selected!.id};for(const k of ['name','notes','operator','client','findings','limitations'])body[k]=$<HTMLInputElement>('capture-'+k).value;selected=await p<Capture>('notes',body);await refresh();message('Capture record saved.');});
  bind('capture-refresh',async()=>{selected=await p<Capture>('refresh',{id:selected!.id});await refresh();});
  bind('capture-report',()=>download('report','flight-report.html'));bind('capture-packet',()=>download('packet','flight-delivery.zip'));
  root.querySelectorAll<HTMLButtonElement>('[data-asset]').forEach(b=>b.onclick=()=>void perform(()=>download('asset',b.dataset.asset!,b.dataset.run,b.dataset.asset)));
  root.querySelectorAll<HTMLButtonElement>('[data-control]').forEach(b=>b.onclick=()=>void perform(async()=>{selected=await p<Capture>('control',{id:selected!.id,run:b.dataset.run,action:b.dataset.control});await refresh();}));
  root.querySelectorAll<HTMLButtonElement>('[data-log]').forEach(b=>b.onclick=()=>void perform(async()=>{const value=await p<unknown>('log?id='+selected!.id+'&run='+b.dataset.log);$('run-log').textContent=Array.isArray(value)?value.join('\n'):JSON.stringify(value,null,2);$('run-log').classList.remove('hidden');}));
 }
 function detail(){const c=selected!;return `<div class="capture-title"><div><small>${esc(c.mission?.name?'LINKED TO '+c.mission.name:'INDEPENDENT CAPTURE')}</small><h1>${esc(c.name)}</h1></div><button id="capture-refresh">Refresh status</button></div><nav class="capture-tabs">${[['media','01 · Media'],['process','02 · Reconstruction'],['outputs','03 · Results'],['report','04 · Report & delivery']].map(([s,l])=>`<button data-stage="${s}" class="${s===stage?'active':''}">${l}</button>`).join('')}</nav>${stage==='media'?media(c):stage==='process'?processForm():stage==='outputs'?outputs(c):reportForm(c)}`;}
 function media(c:Capture){const photo=c.files.filter(f=>f.kind==='photo'),gps=photo.filter(f=>f.gps);return `<div class="capture-drop" id="capture-drop"><b>Drop the flight's media here</b><p>Photos, videos, matching SRT files, ground control and field records. Originals are copied and checksummed.</p><button id="capture-add" class="primary">Choose files</button> <button id="capture-add-folder">Choose folder</button><small>Large files stream in chunks. Source files stay unchanged. Match video.mp4 with video.srt. Use gcp_list.txt for ground control.</small></div><div class="capture-metrics"><article><b>${photo.length}</b>photos</article><article><b>${c.files.filter(f=>f.kind==='video').length}</b>videos</article><article><b>${gps.length} / ${photo.length}</b>photos with readable GPS</article><article><b>${bytes(c.files.reduce((n,f)=>n+f.size,0))}</b>original media</article></div>${photo.length&&gps.length<photo.length?'<p class="notice">Some photos have no readable GPS. Georeferencing may require ground control or a geo.txt file. A successful reconstruction alone does not establish position or accuracy.</p>':''}<div class="media-table"><table><thead><tr><th>Original file</th><th>Type / camera</th><th>Dimensions</th><th>Size</th><th>GPS</th></tr></thead><tbody>${c.files.map(f=>`<tr title="SHA-256: ${f.sha256}"><td>${esc(f.name)}${f.metadataWarning?`<small>${esc(f.metadataWarning)}</small>`:''}</td><td>${esc(f.camera||f.kind)}</td><td>${f.width?f.width+' × '+f.height:'—'}</td><td>${bytes(f.size)}</td><td>${f.gps?'Present':'Not read'}</td></tr>`).join('')}</tbody></table></div>`;}
 function processForm(){return `<div class="processing-form"><section><h2>Choose the work you need</h2><p>Presets are starting points. Camera, overlap, terrain and project size affect the result.</p><label>Processing preset<select id="processing-preset">${Object.entries(engine?.presets||{}).map(([k,v])=>`<option value="${k}" ${k==='survey'?'selected':''}>${esc(v.name)}</option>`).join('')}</select></label><label>Custom engine options<textarea id="custom-options" rows="7" spellcheck="false" placeholder='{"orthophoto-resolution": 3}'>{}</textarea></label><small>Values override the preset. Resolution values are centimeters per pixel. Only options advertised by the running engine are accepted.</small><button id="capture-process" class="primary" ${!engine?.ready?'disabled':''}>Reconstruct this capture</button><p>WebODM also provides GCP editing, image masks, multispectral and thermal workflows, task alignment, full processing options, and task restart controls.</p></section><section><h2>Engine options</h2><button id="processing-options" ${!engine?.ready?'disabled':''}>Load all supported options</button><input id="option-search" placeholder="Search options" aria-label="Search engine options"><div class="engine-options">${options.map(o=>`<article data-option-row><button data-add-option="${esc(o.name)}">Add</button><b>${esc(o.name)}</b><small>${esc(o.type)} · default ${esc(o.value)}</small><p>${esc(o.help)}</p>${o.domain?`<small>${esc(JSON.stringify(o.domain))}</small>`:''}</article>`).join('')}</div></section></div>`;}
 function outputs(c:Capture){return `<p>Open the full WebODM workspace above for interactive 2D/3D maps, measurements, contours, volumes, GCP review, overlays, comparisons and exports.</p>${c.runs.map(r=>`<article class="run-card"><div class="run-heading"><h2>${esc(r.status)}</h2><small>${new Date(r.created).toLocaleString()} · ${r.mode==='cpu'?'CPU':'CUDA enabled'}</small></div><progress max="100" value="${r.status==='Completed'?100:Math.max(0,Math.min(100,(r.progress||0)*100))}"></progress><p>${r.status==='Uploading'?r.uploaded+' / '+r.total+' files uploaded':''}${esc(r.error||'')}</p><div class="run-actions"><button data-log="${r.id}">Processing log</button><button data-control="cancel" data-run="${r.id}" ${!['Queued','Processing'].includes(r.status)?'disabled':''}>Cancel run</button><button data-control="restart" data-run="${r.id}" ${!['Failed','Canceled','Completed'].includes(r.status)?'disabled':''}>Restart run</button></div><div class="asset-grid">${(r.assets||[]).map(a=>`<button data-asset="${esc(a)}" data-run="${r.id}">↓ ${esc(a)}</button>`).join('')||'<p>No completed outputs recorded yet.</p>'}</div></article>`).join('')||'<div class="empty">No reconstruction runs yet. Add media and choose Reconstruction.</div>'}<pre id="run-log" class="run-log hidden"></pre>`;}
 function reportForm(c:Capture){const field=(key:keyof Capture,label:string,large=false)=>`<label>${label}${large?`<textarea id="capture-${key}" rows="4">${esc(c[key])}</textarea>`:`<input id="capture-${key}" value="${esc(c[key])}">`}</label>`;return `<div class="report-form"><section><h2>Give the work context</h2>${field('name','Capture name')}${field('client','Client / project')}${field('operator','Operator / reviewer')}${field('notes','Field notes, capture conditions and control',true)}${field('findings','Reviewed findings',true)}${field('limitations','Limitations, coordinate reference and accuracy evidence',true)}<button id="capture-save-notes" class="primary">Save report record</button></section><section class="delivery-card"><h2>Prepare the handoff</h2><p>The report records the linked plan, imported media checksums, processing settings, output inventory, and your reviewed findings.</p><button id="capture-report">Download printable report</button><button id="capture-packet" class="primary">Download delivery packet</button><p>Open the HTML report in a browser and print to PDF. The ZIP also contains the capture manifest and linked ODP flight project. Save edits before downloading.</p><p>Download large maps, point clouds, models and the engine quality report from Results. Add them to the client delivery alongside this packet.</p><small>Contains flight locations and media metadata. Review before sharing. No survey accuracy is inferred from processing completion.</small></section></div>`;}
 async function upload(files:File[]){if(!selected)throw Error('Create a capture first.');const id=selected.id;const names=new Set<string>();for(const file of files){const key=file.name.toLowerCase();if(names.has(key))throw Error('The selected folders contain duplicate filenames: '+file.name+'. Choose one flight folder at a time.');names.add(key);}let done=0;for(const file of files){if(!/\.(jpe?g|png|tiff?|dng|mp4|mov|lrv|ts|srt|txt|csv|json|geojson|kml|kmz|pdf)$/i.test(file.name))continue;if(selected.files.some(f=>f.name.toLowerCase()===file.name.toLowerCase()))throw Error('File already imported: '+file.name+'. Choose the remaining files, or create a new capture.');for(let offset=0;offset<file.size;offset+=4*1024**2){message(`Importing ${done+1} / ${files.length}: ${file.name} · ${Math.round(offset/file.size*100)}%`);const q=new URLSearchParams({id,name:file.name,offset:String(offset),total:String(file.size)});const r=await fetch('/api/processing/upload?'+q,{method:'POST',headers:{'X-ODP-Token':window.ODP_TOKEN},body:file.slice(offset,offset+4*1024**2)});if(!r.ok)throw Error((await r.json()).error);}done++;}await refresh();message(`Imported ${done} files. Originals retained on this computer.`);}
 async function download(kind:string,name:string,run?:string,asset?:string){const r=await p<{url:string}>('download-ticket',{id:selected!.id,kind,...(run?{run}:{}),...(asset?{asset}:{})});const a=document.createElement('a');a.href=r.url;a.download=name;a.click();message('Download started. Large outputs stream directly to disk.');}

 nav.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.onclick=()=>{const process=b.dataset.workflow==='process';nav.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));document.querySelector('.workspace')!.classList.toggle('hidden',process);root.classList.toggle('hidden',!process);if(poll)clearInterval(poll);poll=null;if(process){void refresh();poll=setInterval(async()=>{if(busy)return;try{engine=await p<Engine>('status');$('engine-status').textContent=engine.message;if(selected&&stage==='outputs'){selected=await p<Capture>('refresh',{id:selected.id});render();}}catch(e){message(String(e),true);}},5000);}else onPlan(b.dataset.workflow==='fly');});
}
